// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rancher2.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterAlterRuleSystemServiceRuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterAlterRuleSystemServiceRuleArgs Empty = new ClusterAlterRuleSystemServiceRuleArgs();

    /**
     * System service rule condition
     * 
     */
    @Import(name="condition")
    private @Nullable Output<String> condition;

    /**
     * @return System service rule condition
     * 
     */
    public Optional<Output<String>> condition() {
        return Optional.ofNullable(this.condition);
    }

    private ClusterAlterRuleSystemServiceRuleArgs() {}

    private ClusterAlterRuleSystemServiceRuleArgs(ClusterAlterRuleSystemServiceRuleArgs $) {
        this.condition = $.condition;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterAlterRuleSystemServiceRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterAlterRuleSystemServiceRuleArgs $;

        public Builder() {
            $ = new ClusterAlterRuleSystemServiceRuleArgs();
        }

        public Builder(ClusterAlterRuleSystemServiceRuleArgs defaults) {
            $ = new ClusterAlterRuleSystemServiceRuleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param condition System service rule condition
         * 
         * @return builder
         * 
         */
        public Builder condition(@Nullable Output<String> condition) {
            $.condition = condition;
            return this;
        }

        /**
         * @param condition System service rule condition
         * 
         * @return builder
         * 
         */
        public Builder condition(String condition) {
            return condition(Output.of(condition));
        }

        public ClusterAlterRuleSystemServiceRuleArgs build() {
            return $;
        }
    }

}
