// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rancher2.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetStorageClassV2PlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetStorageClassV2PlainArgs Empty = new GetStorageClassV2PlainArgs();

    /**
     * The cluster id of the storageClass V2 (string)
     * 
     */
    @Import(name="clusterId", required=true)
    private String clusterId;

    /**
     * @return The cluster id of the storageClass V2 (string)
     * 
     */
    public String clusterId() {
        return this.clusterId;
    }

    /**
     * The name of the storageClass v2 (string)
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return The name of the storageClass v2 (string)
     * 
     */
    public String name() {
        return this.name;
    }

    private GetStorageClassV2PlainArgs() {}

    private GetStorageClassV2PlainArgs(GetStorageClassV2PlainArgs $) {
        this.clusterId = $.clusterId;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetStorageClassV2PlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetStorageClassV2PlainArgs $;

        public Builder() {
            $ = new GetStorageClassV2PlainArgs();
        }

        public Builder(GetStorageClassV2PlainArgs defaults) {
            $ = new GetStorageClassV2PlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param clusterId The cluster id of the storageClass V2 (string)
         * 
         * @return builder
         * 
         */
        public Builder clusterId(String clusterId) {
            $.clusterId = clusterId;
            return this;
        }

        /**
         * @param name The name of the storageClass v2 (string)
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public GetStorageClassV2PlainArgs build() {
            if ($.clusterId == null) {
                throw new MissingRequiredPropertyException("GetStorageClassV2PlainArgs", "clusterId");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetStorageClassV2PlainArgs", "name");
            }
            return $;
        }
    }

}
