provider: rancher2
major-version: 11
setup-script: testing/setup.sh
esc:
    enabled: true
env:
    RANCHER_INSECURE: "true"
    RANCHER_URL: https://localhost # docker
makeTemplate: bridged
pulumiConvert: 1
registryDocs: true
