provider: rancher2
major-version: 6
setup-script: testing/setup.sh
env:
  RANCHER_INSECURE: "true"
  RANCHER_URL: https://localhost # docker
makeTemplate: bridged
pulumiConvert: 1
plugins:
  - name: std
    version: "1.6.2"

  - name: terraform
    version: "1.0.16"
    kind: converter
