// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rancher2.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.rancher2.outputs.ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScanScanConfig;
import com.pulumi.rancher2.outputs.ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScanScheduleConfig;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScan {
    /**
     * @return Enable cluster template revision. Default `true` (bool)
     * 
     */
    private @Nullable Boolean enabled;
    private ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScanScanConfig scanConfig;
    private ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScanScheduleConfig scheduleConfig;

    private ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScan() {}
    /**
     * @return Enable cluster template revision. Default `true` (bool)
     * 
     */
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }
    public ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScanScanConfig scanConfig() {
        return this.scanConfig;
    }
    public ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScanScheduleConfig scheduleConfig() {
        return this.scheduleConfig;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScan defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean enabled;
        private ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScanScanConfig scanConfig;
        private ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScanScheduleConfig scheduleConfig;
        public Builder() {}
        public Builder(ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScan defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.scanConfig = defaults.scanConfig;
    	      this.scheduleConfig = defaults.scheduleConfig;
        }

        @CustomType.Setter
        public Builder enabled(@Nullable Boolean enabled) {
            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder scanConfig(ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScanScanConfig scanConfig) {
            this.scanConfig = Objects.requireNonNull(scanConfig);
            return this;
        }
        @CustomType.Setter
        public Builder scheduleConfig(ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScanScheduleConfig scheduleConfig) {
            this.scheduleConfig = Objects.requireNonNull(scheduleConfig);
            return this;
        }
        public ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScan build() {
            final var o = new ClusterTemplateTemplateRevisionClusterConfigScheduledClusterScan();
            o.enabled = enabled;
            o.scanConfig = scanConfig;
            o.scheduleConfig = scheduleConfig;
            return o;
        }
    }
}
