// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rancher2.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClusterGkeConfigV2ClusterAddons {
    /**
     * @return Enable GKE horizontal pod autoscaling. Default: `false` (bool)
     * 
     */
    private final @Nullable Boolean horizontalPodAutoscaling;
    /**
     * @return Enable GKE HTTP load balancing. Default: `false` (bool)
     * 
     */
    private final @Nullable Boolean httpLoadBalancing;
    /**
     * @return Enable GKE network policy config. Default: `false` (bool)
     * 
     */
    private final @Nullable Boolean networkPolicyConfig;

    @CustomType.Constructor
    private ClusterGkeConfigV2ClusterAddons(
        @CustomType.Parameter("horizontalPodAutoscaling") @Nullable Boolean horizontalPodAutoscaling,
        @CustomType.Parameter("httpLoadBalancing") @Nullable Boolean httpLoadBalancing,
        @CustomType.Parameter("networkPolicyConfig") @Nullable Boolean networkPolicyConfig) {
        this.horizontalPodAutoscaling = horizontalPodAutoscaling;
        this.httpLoadBalancing = httpLoadBalancing;
        this.networkPolicyConfig = networkPolicyConfig;
    }

    /**
     * @return Enable GKE horizontal pod autoscaling. Default: `false` (bool)
     * 
     */
    public Optional<Boolean> horizontalPodAutoscaling() {
        return Optional.ofNullable(this.horizontalPodAutoscaling);
    }
    /**
     * @return Enable GKE HTTP load balancing. Default: `false` (bool)
     * 
     */
    public Optional<Boolean> httpLoadBalancing() {
        return Optional.ofNullable(this.httpLoadBalancing);
    }
    /**
     * @return Enable GKE network policy config. Default: `false` (bool)
     * 
     */
    public Optional<Boolean> networkPolicyConfig() {
        return Optional.ofNullable(this.networkPolicyConfig);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterGkeConfigV2ClusterAddons defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Boolean horizontalPodAutoscaling;
        private @Nullable Boolean httpLoadBalancing;
        private @Nullable Boolean networkPolicyConfig;

        public Builder() {
    	      // Empty
        }

        public Builder(ClusterGkeConfigV2ClusterAddons defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.horizontalPodAutoscaling = defaults.horizontalPodAutoscaling;
    	      this.httpLoadBalancing = defaults.httpLoadBalancing;
    	      this.networkPolicyConfig = defaults.networkPolicyConfig;
        }

        public Builder horizontalPodAutoscaling(@Nullable Boolean horizontalPodAutoscaling) {
            this.horizontalPodAutoscaling = horizontalPodAutoscaling;
            return this;
        }
        public Builder httpLoadBalancing(@Nullable Boolean httpLoadBalancing) {
            this.httpLoadBalancing = httpLoadBalancing;
            return this;
        }
        public Builder networkPolicyConfig(@Nullable Boolean networkPolicyConfig) {
            this.networkPolicyConfig = networkPolicyConfig;
            return this;
        }        public ClusterGkeConfigV2ClusterAddons build() {
            return new ClusterGkeConfigV2ClusterAddons(horizontalPodAutoscaling, httpLoadBalancing, networkPolicyConfig);
        }
    }
}
