// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rancher2.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetClusterV2RkeConfigEtcdS3Config {
    /**
     * @return ETCD snapshot S3 bucket
     * 
     */
    private String bucket;
    /**
     * @return ETCD snapshot S3 cloud credential name
     * 
     */
    private @Nullable String cloudCredentialName;
    /**
     * @return ETCD snapshot S3 endpoint
     * 
     */
    private String endpoint;
    /**
     * @return ETCD snapshot S3 endpoint CA
     * 
     */
    private @Nullable String endpointCa;
    /**
     * @return ETCD snapshot S3 folder
     * 
     */
    private @Nullable String folder;
    /**
     * @return ETCD snapshot S3 region
     * 
     */
    private @Nullable String region;
    /**
     * @return Disable ETCD skip ssl verify
     * 
     */
    private @Nullable Boolean skipSslVerify;

    private GetClusterV2RkeConfigEtcdS3Config() {}
    /**
     * @return ETCD snapshot S3 bucket
     * 
     */
    public String bucket() {
        return this.bucket;
    }
    /**
     * @return ETCD snapshot S3 cloud credential name
     * 
     */
    public Optional<String> cloudCredentialName() {
        return Optional.ofNullable(this.cloudCredentialName);
    }
    /**
     * @return ETCD snapshot S3 endpoint
     * 
     */
    public String endpoint() {
        return this.endpoint;
    }
    /**
     * @return ETCD snapshot S3 endpoint CA
     * 
     */
    public Optional<String> endpointCa() {
        return Optional.ofNullable(this.endpointCa);
    }
    /**
     * @return ETCD snapshot S3 folder
     * 
     */
    public Optional<String> folder() {
        return Optional.ofNullable(this.folder);
    }
    /**
     * @return ETCD snapshot S3 region
     * 
     */
    public Optional<String> region() {
        return Optional.ofNullable(this.region);
    }
    /**
     * @return Disable ETCD skip ssl verify
     * 
     */
    public Optional<Boolean> skipSslVerify() {
        return Optional.ofNullable(this.skipSslVerify);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetClusterV2RkeConfigEtcdS3Config defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String bucket;
        private @Nullable String cloudCredentialName;
        private String endpoint;
        private @Nullable String endpointCa;
        private @Nullable String folder;
        private @Nullable String region;
        private @Nullable Boolean skipSslVerify;
        public Builder() {}
        public Builder(GetClusterV2RkeConfigEtcdS3Config defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.bucket = defaults.bucket;
    	      this.cloudCredentialName = defaults.cloudCredentialName;
    	      this.endpoint = defaults.endpoint;
    	      this.endpointCa = defaults.endpointCa;
    	      this.folder = defaults.folder;
    	      this.region = defaults.region;
    	      this.skipSslVerify = defaults.skipSslVerify;
        }

        @CustomType.Setter
        public Builder bucket(String bucket) {
            if (bucket == null) {
              throw new MissingRequiredPropertyException("GetClusterV2RkeConfigEtcdS3Config", "bucket");
            }
            this.bucket = bucket;
            return this;
        }
        @CustomType.Setter
        public Builder cloudCredentialName(@Nullable String cloudCredentialName) {

            this.cloudCredentialName = cloudCredentialName;
            return this;
        }
        @CustomType.Setter
        public Builder endpoint(String endpoint) {
            if (endpoint == null) {
              throw new MissingRequiredPropertyException("GetClusterV2RkeConfigEtcdS3Config", "endpoint");
            }
            this.endpoint = endpoint;
            return this;
        }
        @CustomType.Setter
        public Builder endpointCa(@Nullable String endpointCa) {

            this.endpointCa = endpointCa;
            return this;
        }
        @CustomType.Setter
        public Builder folder(@Nullable String folder) {

            this.folder = folder;
            return this;
        }
        @CustomType.Setter
        public Builder region(@Nullable String region) {

            this.region = region;
            return this;
        }
        @CustomType.Setter
        public Builder skipSslVerify(@Nullable Boolean skipSslVerify) {

            this.skipSslVerify = skipSslVerify;
            return this;
        }
        public GetClusterV2RkeConfigEtcdS3Config build() {
            final var _resultValue = new GetClusterV2RkeConfigEtcdS3Config();
            _resultValue.bucket = bucket;
            _resultValue.cloudCredentialName = cloudCredentialName;
            _resultValue.endpoint = endpoint;
            _resultValue.endpointCa = endpointCa;
            _resultValue.folder = folder;
            _resultValue.region = region;
            _resultValue.skipSslVerify = skipSslVerify;
            return _resultValue;
        }
    }
}
