// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rancher2.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetProjectAlertRuleMetricRule {
    private final @Nullable String comparison;
    private final @Nullable String description;
    private final String duration;
    private final String expression;
    private final Double thresholdValue;

    @CustomType.Constructor
    private GetProjectAlertRuleMetricRule(
        @CustomType.Parameter("comparison") @Nullable String comparison,
        @CustomType.Parameter("description") @Nullable String description,
        @CustomType.Parameter("duration") String duration,
        @CustomType.Parameter("expression") String expression,
        @CustomType.Parameter("thresholdValue") Double thresholdValue) {
        this.comparison = comparison;
        this.description = description;
        this.duration = duration;
        this.expression = expression;
        this.thresholdValue = thresholdValue;
    }

    public Optional<String> comparison() {
        return Optional.ofNullable(this.comparison);
    }
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }
    public String duration() {
        return this.duration;
    }
    public String expression() {
        return this.expression;
    }
    public Double thresholdValue() {
        return this.thresholdValue;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetProjectAlertRuleMetricRule defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable String comparison;
        private @Nullable String description;
        private String duration;
        private String expression;
        private Double thresholdValue;

        public Builder() {
    	      // Empty
        }

        public Builder(GetProjectAlertRuleMetricRule defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.comparison = defaults.comparison;
    	      this.description = defaults.description;
    	      this.duration = defaults.duration;
    	      this.expression = defaults.expression;
    	      this.thresholdValue = defaults.thresholdValue;
        }

        public Builder comparison(@Nullable String comparison) {
            this.comparison = comparison;
            return this;
        }
        public Builder description(@Nullable String description) {
            this.description = description;
            return this;
        }
        public Builder duration(String duration) {
            this.duration = Objects.requireNonNull(duration);
            return this;
        }
        public Builder expression(String expression) {
            this.expression = Objects.requireNonNull(expression);
            return this;
        }
        public Builder thresholdValue(Double thresholdValue) {
            this.thresholdValue = Objects.requireNonNull(thresholdValue);
            return this;
        }        public GetProjectAlertRuleMetricRule build() {
            return new GetProjectAlertRuleMetricRule(comparison, description, duration, expression, thresholdValue);
        }
    }
}
