// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rancher2.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetPodSecurityPolicyTemplateAllowedCsiDriver {
    /**
     * @return The name of the PodSecurityPolicyTemplate (string)
     * 
     */
    private String name;

    private GetPodSecurityPolicyTemplateAllowedCsiDriver() {}
    /**
     * @return The name of the PodSecurityPolicyTemplate (string)
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPodSecurityPolicyTemplateAllowedCsiDriver defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        public Builder() {}
        public Builder(GetPodSecurityPolicyTemplateAllowedCsiDriver defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        public GetPodSecurityPolicyTemplateAllowedCsiDriver build() {
            final var _resultValue = new GetPodSecurityPolicyTemplateAllowedCsiDriver();
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
