// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.rancher2.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@CustomType
public final class GetStorageClassV2Result {
    /**
     * @return (Computed) Is the provisioner of the storageClass v2 allowing volume expansion? (bool)
     * 
     */
    private final Boolean allowVolumeExpansion;
    /**
     * @return (Computed) Annotations for the storageClass v2 (map)
     * 
     */
    private final Map<String,Object> annotations;
    private final String clusterId;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private final String id;
    /**
     * @return (Computed) The provisioner of the storageClass v2 (string)
     * 
     */
    private final String k8sProvisioner;
    /**
     * @return (Computed) Labels for the storageClass v2 (map)
     * 
     */
    private final Map<String,Object> labels;
    /**
     * @return (Computed) The mount options for storageClass v2 (list)
     * 
     */
    private final List<String> mountOptions;
    private final String name;
    /**
     * @return (Computed) The parameters for storageClass v2 (string)
     * 
     */
    private final Map<String,Object> parameters;
    /**
     * @return (Computed) The reclaim policy for storageClass v2 (string)
     * 
     */
    private final String reclaimPolicy;
    /**
     * @return (Computed) The k8s resource version (string)
     * 
     */
    private final String resourceVersion;
    /**
     * @return (Computed) The volume binding mode for storageClass v2 (string)
     * 
     */
    private final String volumeBindingMode;

    @CustomType.Constructor
    private GetStorageClassV2Result(
        @CustomType.Parameter("allowVolumeExpansion") Boolean allowVolumeExpansion,
        @CustomType.Parameter("annotations") Map<String,Object> annotations,
        @CustomType.Parameter("clusterId") String clusterId,
        @CustomType.Parameter("id") String id,
        @CustomType.Parameter("k8sProvisioner") String k8sProvisioner,
        @CustomType.Parameter("labels") Map<String,Object> labels,
        @CustomType.Parameter("mountOptions") List<String> mountOptions,
        @CustomType.Parameter("name") String name,
        @CustomType.Parameter("parameters") Map<String,Object> parameters,
        @CustomType.Parameter("reclaimPolicy") String reclaimPolicy,
        @CustomType.Parameter("resourceVersion") String resourceVersion,
        @CustomType.Parameter("volumeBindingMode") String volumeBindingMode) {
        this.allowVolumeExpansion = allowVolumeExpansion;
        this.annotations = annotations;
        this.clusterId = clusterId;
        this.id = id;
        this.k8sProvisioner = k8sProvisioner;
        this.labels = labels;
        this.mountOptions = mountOptions;
        this.name = name;
        this.parameters = parameters;
        this.reclaimPolicy = reclaimPolicy;
        this.resourceVersion = resourceVersion;
        this.volumeBindingMode = volumeBindingMode;
    }

    /**
     * @return (Computed) Is the provisioner of the storageClass v2 allowing volume expansion? (bool)
     * 
     */
    public Boolean allowVolumeExpansion() {
        return this.allowVolumeExpansion;
    }
    /**
     * @return (Computed) Annotations for the storageClass v2 (map)
     * 
     */
    public Map<String,Object> annotations() {
        return this.annotations;
    }
    public String clusterId() {
        return this.clusterId;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return (Computed) The provisioner of the storageClass v2 (string)
     * 
     */
    public String k8sProvisioner() {
        return this.k8sProvisioner;
    }
    /**
     * @return (Computed) Labels for the storageClass v2 (map)
     * 
     */
    public Map<String,Object> labels() {
        return this.labels;
    }
    /**
     * @return (Computed) The mount options for storageClass v2 (list)
     * 
     */
    public List<String> mountOptions() {
        return this.mountOptions;
    }
    public String name() {
        return this.name;
    }
    /**
     * @return (Computed) The parameters for storageClass v2 (string)
     * 
     */
    public Map<String,Object> parameters() {
        return this.parameters;
    }
    /**
     * @return (Computed) The reclaim policy for storageClass v2 (string)
     * 
     */
    public String reclaimPolicy() {
        return this.reclaimPolicy;
    }
    /**
     * @return (Computed) The k8s resource version (string)
     * 
     */
    public String resourceVersion() {
        return this.resourceVersion;
    }
    /**
     * @return (Computed) The volume binding mode for storageClass v2 (string)
     * 
     */
    public String volumeBindingMode() {
        return this.volumeBindingMode;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetStorageClassV2Result defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private Boolean allowVolumeExpansion;
        private Map<String,Object> annotations;
        private String clusterId;
        private String id;
        private String k8sProvisioner;
        private Map<String,Object> labels;
        private List<String> mountOptions;
        private String name;
        private Map<String,Object> parameters;
        private String reclaimPolicy;
        private String resourceVersion;
        private String volumeBindingMode;

        public Builder() {
    	      // Empty
        }

        public Builder(GetStorageClassV2Result defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.allowVolumeExpansion = defaults.allowVolumeExpansion;
    	      this.annotations = defaults.annotations;
    	      this.clusterId = defaults.clusterId;
    	      this.id = defaults.id;
    	      this.k8sProvisioner = defaults.k8sProvisioner;
    	      this.labels = defaults.labels;
    	      this.mountOptions = defaults.mountOptions;
    	      this.name = defaults.name;
    	      this.parameters = defaults.parameters;
    	      this.reclaimPolicy = defaults.reclaimPolicy;
    	      this.resourceVersion = defaults.resourceVersion;
    	      this.volumeBindingMode = defaults.volumeBindingMode;
        }

        public Builder allowVolumeExpansion(Boolean allowVolumeExpansion) {
            this.allowVolumeExpansion = Objects.requireNonNull(allowVolumeExpansion);
            return this;
        }
        public Builder annotations(Map<String,Object> annotations) {
            this.annotations = Objects.requireNonNull(annotations);
            return this;
        }
        public Builder clusterId(String clusterId) {
            this.clusterId = Objects.requireNonNull(clusterId);
            return this;
        }
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public Builder k8sProvisioner(String k8sProvisioner) {
            this.k8sProvisioner = Objects.requireNonNull(k8sProvisioner);
            return this;
        }
        public Builder labels(Map<String,Object> labels) {
            this.labels = Objects.requireNonNull(labels);
            return this;
        }
        public Builder mountOptions(List<String> mountOptions) {
            this.mountOptions = Objects.requireNonNull(mountOptions);
            return this;
        }
        public Builder mountOptions(String... mountOptions) {
            return mountOptions(List.of(mountOptions));
        }
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        public Builder parameters(Map<String,Object> parameters) {
            this.parameters = Objects.requireNonNull(parameters);
            return this;
        }
        public Builder reclaimPolicy(String reclaimPolicy) {
            this.reclaimPolicy = Objects.requireNonNull(reclaimPolicy);
            return this;
        }
        public Builder resourceVersion(String resourceVersion) {
            this.resourceVersion = Objects.requireNonNull(resourceVersion);
            return this;
        }
        public Builder volumeBindingMode(String volumeBindingMode) {
            this.volumeBindingMode = Objects.requireNonNull(volumeBindingMode);
            return this;
        }        public GetStorageClassV2Result build() {
            return new GetStorageClassV2Result(allowVolumeExpansion, annotations, clusterId, id, k8sProvisioner, labels, mountOptions, name, parameters, reclaimPolicy, resourceVersion, volumeBindingMode);
        }
    }
}
