// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rancher2.Outputs
{

    [OutputType]
    public sealed class ClusterRkeConfigMonitoring
    {
        /// <summary>
        /// RKE monitoring node selector (map)
        /// </summary>
        public readonly ImmutableDictionary<string, object>? NodeSelector;
        /// <summary>
        /// RKE options for network (map)
        /// </summary>
        public readonly ImmutableDictionary<string, object>? Options;
        /// <summary>
        /// RKE monitoring provider (string)
        /// </summary>
        public readonly string? Provider;
        /// <summary>
        /// RKE monitoring replicas (int)
        /// </summary>
        public readonly int? Replicas;
        /// <summary>
        /// Monitoring add-on tolerations
        /// </summary>
        public readonly ImmutableArray<Outputs.ClusterRkeConfigMonitoringToleration> Tolerations;
        /// <summary>
        /// Update deployment strategy
        /// </summary>
        public readonly Outputs.ClusterRkeConfigMonitoringUpdateStrategy? UpdateStrategy;

        [OutputConstructor]
        private ClusterRkeConfigMonitoring(
            ImmutableDictionary<string, object>? nodeSelector,

            ImmutableDictionary<string, object>? options,

            string? provider,

            int? replicas,

            ImmutableArray<Outputs.ClusterRkeConfigMonitoringToleration> tolerations,

            Outputs.ClusterRkeConfigMonitoringUpdateStrategy? updateStrategy)
        {
            NodeSelector = nodeSelector;
            Options = options;
            Provider = provider;
            Replicas = replicas;
            Tolerations = tolerations;
            UpdateStrategy = updateStrategy;
        }
    }
}
