// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rancher2.Outputs
{

    [OutputType]
    public sealed class ClusterTemplateTemplateRevisionClusterConfigRkeConfigPrivateRegistryEcrCredentialPlugin
    {
        public readonly string? AwsAccessKeyId;
        public readonly string? AwsSecretAccessKey;
        public readonly string? AwsSessionToken;

        [OutputConstructor]
        private ClusterTemplateTemplateRevisionClusterConfigRkeConfigPrivateRegistryEcrCredentialPlugin(
            string? awsAccessKeyId,

            string? awsSecretAccessKey,

            string? awsSessionToken)
        {
            AwsAccessKeyId = awsAccessKeyId;
            AwsSecretAccessKey = awsSecretAccessKey;
            AwsSessionToken = awsSessionToken;
        }
    }
}
