// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rancher2.Outputs
{

    [OutputType]
    public sealed class GetClusterClusterMonitoringInputResult
    {
        /// <summary>
        /// Answers for monitor input
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Answers;
        /// <summary>
        /// Monitoring version
        /// </summary>
        public readonly string? Version;

        [OutputConstructor]
        private GetClusterClusterMonitoringInputResult(
            ImmutableDictionary<string, string>? answers,

            string? version)
        {
            Answers = answers;
            Version = version;
        }
    }
}
