#!/bin/bash
set -ef -o pipefail

WORKSPACE=$(./scripts/get-workspace)
echo "Using workspace: ${WORKSPACE}"
mkdir -p $WORKSPACE/nuget
find . -name '*.nupkg' -print -exec cp -p {} ${WORKSPACE}/nuget \;
