// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package rancher2

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupRegistry(ctx *pulumi.Context, args *LookupRegistryArgs, opts ...pulumi.InvokeOption) (*LookupRegistryResult, error) {
	var rv LookupRegistryResult
	err := ctx.Invoke("rancher2:index/getRegistry:getRegistry", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getRegistry.
type LookupRegistryArgs struct {
	Name        string  `pulumi:"name"`
	NamespaceId *string `pulumi:"namespaceId"`
	ProjectId   string  `pulumi:"projectId"`
}

// A collection of values returned by getRegistry.
type LookupRegistryResult struct {
	Annotations map[string]interface{} `pulumi:"annotations"`
	Description string                 `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id          string                 `pulumi:"id"`
	Labels      map[string]interface{} `pulumi:"labels"`
	Name        string                 `pulumi:"name"`
	NamespaceId *string                `pulumi:"namespaceId"`
	ProjectId   string                 `pulumi:"projectId"`
	Registries  []GetRegistryRegistry  `pulumi:"registries"`
}
