// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Rancher2.Inputs
{

    public sealed class ClusterRkeConfigCloudProviderOpenstackCloudProviderGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// (list maxitems:1)
        /// </summary>
        [Input("blockStorage")]
        public Input<Inputs.ClusterRkeConfigCloudProviderOpenstackCloudProviderBlockStorageGetArgs>? BlockStorage { get; set; }

        /// <summary>
        /// (list maxitems:1)
        /// </summary>
        [Input("global", required: true)]
        public Input<Inputs.ClusterRkeConfigCloudProviderOpenstackCloudProviderGlobalGetArgs> Global { get; set; } = null!;

        /// <summary>
        /// (list maxitems:1)
        /// </summary>
        [Input("loadBalancer")]
        public Input<Inputs.ClusterRkeConfigCloudProviderOpenstackCloudProviderLoadBalancerGetArgs>? LoadBalancer { get; set; }

        /// <summary>
        /// (list maxitems:1)
        /// </summary>
        [Input("metadata")]
        public Input<Inputs.ClusterRkeConfigCloudProviderOpenstackCloudProviderMetadataGetArgs>? Metadata { get; set; }

        /// <summary>
        /// (list maxitems:1)
        /// </summary>
        [Input("route")]
        public Input<Inputs.ClusterRkeConfigCloudProviderOpenstackCloudProviderRouteGetArgs>? Route { get; set; }

        public ClusterRkeConfigCloudProviderOpenstackCloudProviderGetArgs()
        {
        }
    }
}
