name: ci # FIXME: what should we name this?
on:
  pull_request:
    branches:
      - master
  push:
    tags: [ "v*" ]

env:
  GO111MODULE: on
  PROVIDER: rancher2


jobs:
  prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.x'
      - name: Download dependencies
        run: |
          cd provider
          go mod tidy
          go mod download
      - name: Build tfgen & provider binaries
        run: make provider
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pulumi-${{ env.PROVIDER}}
          path: ${{ github.workspace }}/bin
  
