env:
  GO111MODULE: "on"
  PROVIDER: rancher2
jobs:
  build_sdk:
    runs-on: ubuntu-latest
  lint:
    container: golangci/golangci-lint:v1.25.1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  prerequisites:
    runs-on: ubuntu-latest
  test:
    runs-on: ubuntu-latest
name: ci
"on":
  pull_request:
    branches:
    - master
  push:
    tags:
    - v*
