name: ci # FIXME: what should we name this?
on:
  pull_request:
    branches:
      - master
  push:
    tags: [ "v*" ]

env:
  GO111MODULE: on
  PROVIDER: rancher2


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Insert more steps here!
  prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.x'
      - name: Download dependencies
        run: |
          cd provider
          go mod tidy
          go mod download
      - name: Build tfgen & provider binaries
        run: make provider
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pulumi-${{ env.PROVIDER}}
          path: ${{ github.workspace }}/bin
  nodejs:
    runs-on: ubuntu-latest
    needs: prerequisites
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          path: ${{ github.workspace }}/bin
      - name: Restore binary perms
        run: find ${{ github.workspace }}/bin -name 'pulumi-tfgen-rancher2' -name 'pulumi-resource-rancher2' -exec chmod +x {} \;
      - name: Install tf2pulumi
        uses: pulumi/action-install-tf2pulumi@releases/v1
        with:
          tf2pulumi-version: 0.7.0
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Build SDK
        run: make build_node
